🌐 [i18n-KO] Translated `git_vs_http.md` to Korean
huggingface/huggingface_hub pull request #1862
Opened 2023-11-26 03:14 UTC by heuristicwave

# What does this PR do?

Translated the `git_vs_http.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [X] Check for missing / redundant translations (번역 누락/중복 검사)
- [X] Grammar Check (맞춤법 검사)
- [X] Review or Add new terms to glossary (용어 확인 및 추가)
- [X] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [X] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

May you please review this PR? @nuatmochoi, @mjk0618, @harheem, @wonhyeongseo, @sim-so

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-11-26 11:34 UTC, sim-so requested changes
안녕하세요, 지훈님!
오랜만에 번역 리뷰 요청을 받아 반가운 마음에 리뷰하러 뛰어왔습니다 😆

우선 주요 제안 사항은 다음 두 가지입니다!
- 일관된 표현으로 번역하기: `push`/`푸시`
- Hugging Face 생태계 내 고유명사는 그대로 사용하기: `Hugging Face Hub`

그 외에는 모두 문장 다듬기에 대한 의견이예요. 제가 읽었을 때 편안한 문장으로 바꾸어 보았습니다만, 다른 의견이 있다면 알려주세요! 

늘 고맙습니다 🙌

2023-11-27 10:56 UTC, gabrielwithappy reviewed
I added my comment! :-)

2023-11-27 10:56 UTC, gabrielwithappy commented on docs/source/ko/concepts/git_vs_http.md
> +[`HfApi`]를 사용하면 변경 사항을 pull하고 push하고, PR, 태그 및 브랜치로 작업하고, 토론과 상호 작용하는 등의 작업을 할 수 있습니다.
개인적으로는 문서에서 `git` 으로 사용했기에 push, pull로 사용해도 통일감 있을 것 같습니다.

2023-12-05 02:20 UTC, nuatmochoi commented on docs/source/ko/concepts/git_vs_http.md
> +워크플로에서 로컬로 `git` 명령을 사용하는 것이 합당한 경우 언제든지 가능합니다.
맥락상 일반 명사로서의 workflows로 쓰인 것으로 생각됩니다:)

2023-12-05 07:22 UTC, heuristicwave commented on docs/source/ko/concepts/git_vs_http.md
> +[`HfApi`]를 사용하면 변경 사항을 pull하고 push하고, PR, 태그 및 브랜치로 작업하고, 토론과 상호 작용하는 등의 작업을 할 수 있습니다.
두분다 의견 감사합니다! push, pull로 통일해두겠습니다.

2023-12-05 07:29 UTC, heuristicwave commented on docs/source/ko/concepts/git_vs_http.md
> +워크플로에서 로컬로 `git` 명령을 사용하는 것이 합당한 경우 언제든지 가능합니다.
일반 명사가 맞는 것 같습니다. 주신 의견과 더불어, TTA정보통신용어사전의 정의된 용어인 워크플로우로 변경하겠습니다.

2023-12-05 07:34 UTC, heuristicwave reviewed
fix: resolve suggestions

2023-12-05 07:34 UTC, heuristicwave commented on docs/source/ko/concepts/git_vs_http.md
> +작업 흐름 상 합당하다면 언제든 로컬에서 `git` 명령을 사용할 수 있습니다.
```suggestion
워크플로우 상 합당하다면 언제든 로컬에서 `git` 명령을 사용할 수 있습니다.
```

2023-12-05 07:34 UTC, heuristicwave commented on docs/source/ko/concepts/git_vs_http.md
> +이는 각 개발자가 자체 로컬 복사본을 유지하고 기능을 개발할 때 변경 사항을 푸시하는 전통적인 소프트웨어 개발과 유사합니다.
```suggestion
이는 각 개발자가 자체 로컬 복사본을 유지하고 기능을 개발할 때 변경 사항을 push하는 전통적인 소프트웨어 개발과 유사합니다.
```

2023-12-05 07:34 UTC, heuristicwave commented on docs/source/ko/concepts/git_vs_http.md
> +[`HfApi`] 클래스는 파일 다운로드 및 푸시, 브랜치 및 태그 생성과 같은 git 기반 접근 방식과 동일한 기능을 제공하지만, 동기화 상태를 유지해야 하는 로컬 폴더가 필요하지 않습니다.
```suggestion
[`HfApi`] 클래스는 파일 다운로드 및 push, 브랜치 및 태그 생성과 같은 git 기반 접근 방식과 동일한 기능을 제공하지만, 동기화 상태를 유지해야 하는 로컬 폴더가 필요하지 않습니다.
```

2023-12-05 07:38 UTC, heuristicwave commented
@sim-so 꼼꼼한 리뷰와 @gabrielwithappy 좋은 의견 감사합니다!
의견 주신 내용을 모두 반영했습니다. 문제가 없다면 금주 내로 마치도록 하겠습니다!!

2023-12-13 08:22 UTC, Wauplin commented
Hey there! Good community work here! Love to see that :hugs: 
@heuristicwave you marked the PR as "ready for review". From a technical point of view the PR looks good and we can merge it right now if you want. From a content point of view, please let me know if it's all good or if you'd like a last review from another Korean-speaking contributor. Thank you!

2023-12-13 08:25 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/huggingface_hub/pr_1862). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2023-12-18 13:11 UTC, Wauplin commented
Thanks everyone that worked or reviewed on this PR! :heart: 
I got confirmation from @heuristicwave that it's now in a good state so let's merge it! :hugs:

2023-12-18 13:11 UTC, Wauplin approved these changes
Thanks everyone that worked or reviewed on this PR! ❤️
I got confirmation from @heuristicwave that it's now in a good state so let's merge it! 🤗

2023-12-18 13:11 UTC, merged

2023-12-18 13:17 UTC, heuristicwave commented
Thank you! @Wauplin
Sorry for the late check. See you in another PR :)