Bug - [AsyncInferenceClient] - use proxy set in var env
huggingface/huggingface_hub pull request #2421
Opened 2024-07-25 10:01 UTC by morgandiverrez

The AsyncInferenceClient doesn't use proxies set in environment variables. 
It uses aiohttp but doesn't set the trust_env parameter to True.

this PR set trust_env parameter to True 

issue : [AsyncInferenceClient doesn't use proxies set in environment variables #2420](https://github.com/huggingface/huggingface_hub/issues/2420)

2024-07-31 08:29 UTC, Benvii requested changes
Prevent the breaking change for aiohttp default trust_env is False see my suggestion

2024-07-31 08:29 UTC, Benvii commented on src/huggingface_hub/inference/_generated/_async_client.py
> +        trust_env: bool = True,
Breaking change, default value is False

```suggestion
        trust_env: bool = False, # Default value False documented here https://github.com/aio-libs/aiohttp/blob/v3.10.0/docs/client_reference.rst?plain=1#L195 
```

2024-07-31 08:55 UTC, morgandiverrez commented on src/huggingface_hub/inference/_generated/_async_client.py
> +        trust_env: bool = True,
Yes, thank you, error during testing.

2024-08-01 11:36 UTC, Benvii approved these changes
Thanks @morgandiverrez, looks good to me 👍️.

I saw that @Wauplin worked on this files a few weeks ago, thanks in advance for taking a look at this small PR.
Really helpful fix for those working under corporate proxy that want to take advantage of existing environment variables.

2024-08-06 08:32 UTC, morgandiverrez commented
hello @severo @XciD , is it possible to taking a look at this small PR, it's really helpful fix

2024-08-13 13:09 UTC, Wauplin commented
@morgandiverrez @Benvii thanks for the PR and your inputs and sorry for the delay! I'm having a look at it right now :)

2024-08-13 14:17 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/huggingface_hub/pr_2421). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-08-13 14:17 UTC, Wauplin approved these changes
@morgandiverrez I hope you don't mind, I pushed commits to your PR. Changing stuff in `AsyncClientInference` without changing `InferenceClient` is a bit more complex/annoying as it requires to update a generating script. Anyway, now we should have something good. I didn't want to add `trust_env` to `InferenceClient` since this PR is mostly about `AsyncInferenceClient`. 

New commits:
- Do not modify `InferenceClient` https://github.com/huggingface/huggingface_hub/pull/2421/commits/263d64b276060f6b2e50329c290175ea72a27aec
- Add `trust_env` parameter + respect it in `AsyncInferenceClient` https://github.com/huggingface/huggingface_hub/pull/2421/commits/15ba44a715bd70451c6b039a32ef4ae2f7c1b3fb (also updating the generation script)
- (misc) add docstring + clean newlines https://github.com/huggingface/huggingface_hub/pull/2421/commits/cd47edbd81c3401a5d31d661b83314247fae1b49 https://github.com/huggingface/huggingface_hub/pull/2421/commits/392e96e93530d27798c4d91c960b59a2744b1114

Once the CI is green, I think we'll be good to merge.

2024-08-13 14:20 UTC, Wauplin commented
Failing tests are unrelated so let's merge this :)

2024-08-13 14:20 UTC, merged