Adding `api-inference-community` to `huggingface_hub`.
huggingface/huggingface_hub pull request #48
Opened 2021-05-20 14:26 UTC by Narsil

- The idea is to make all external contributions centralized.
- Moved the quality checks (could make them uniform later)
- `api-inference-community` should be relatively independant from `huggingface_hub` still.

2021-05-20 14:34 UTC, julien-c commented
Thanks! Looks good to me but adding @LysandreJik and @n1t0 to the party

2021-05-20 14:37 UTC, julien-c commented
Does the CI take a long time? If it does, maybe we'll want to restrict the Inference-API's CI to changes to that folder.

2021-05-21 07:35 UTC, LysandreJik approved these changes
Cool, looking forward to having everything centralized.

2021-05-21 08:40 UTC, Narsil commented
Not sure how easy to run conditional actions but if it's easy then yes let's do it !

Otherwise the CI is super fast as we only run the package CI, everything else is considered "slow" as it would require model downloads (and I don't want to force users to test against dummy models as it is a bit more complex to do).

Before deployment, we run the `test_dockers` slow CI which actually build the container + run the test suite on those with a live model. We can do that framework per framework making it livable (running tests against all frameworks all the time seems a bit like a waste since we're relying on docker to make sure no unforeseen change happens within the API)

Conditional full docker tests would be the best so that PR creators can be alerted early if something doesn't fit.

2021-05-21 09:23 UTC, julien-c requested changes

2021-05-21 09:23 UTC, julien-c commented on .github/workflows/python-api-quality.yaml
> +name: Check code quality
```suggestion
name: Inference API code quality
```

2021-05-21 09:23 UTC, julien-c commented on .github/workflows/python-api-tests.yaml
> +name: Python-tests
```suggestion
name: Inference API Python-tests
```

2021-05-21 09:23 UTC, julien-c commented on .github/workflows/python-api-quality.yaml
> +on: push
```suggestion
on:
  push:
    paths:
      - "api-inference-community/**"
```

2021-05-21 09:23 UTC, julien-c commented on .github/workflows/python-api-tests.yaml
> +      - "*"
```suggestion
on:
  push:
    paths:
      - "api-inference-community/**"
```

2021-05-21 09:23 UTC, julien-c commented on README.md
> +## API integration into the huggingface.co hub
```suggestion
## Inference API integration into the huggingface.co hub
```

2021-05-21 09:23 UTC, julien-c commented on README.md
> +In order to get functional widgets on the hub for your models check out this [doc](https://github.com/huggingface/huggingface_hub/tree/master/api-inference-community)
```suggestion
In order to get a functional Inference API on the hub for your models (and thus, cool working widgets!) check out this [doc](https://github.com/huggingface/huggingface_hub/tree/master/api-inference-community)
```

2021-05-25 12:59 UTC, Narsil commented
Hi @julien-c do you think the changes made are OK?

I added a simple docker test only for allennlp (afaik, I would need one for each framework, because we can't have multiple `on` clauses in a single yaml file).

Also I am not 100% sure about this docker because it does not seem to run on this PR, is that normal ? I though GH actions should run on current PR, but maybe I'm wrong.

2021-05-25 13:30 UTC, julien-c commented
not sure why the CI suite doesn't run, maybe it will after we merge this first PR? or maybe add a `pull_request:` event clause with the same paths?

2021-05-25 13:47 UTC, LysandreJik approved these changes
LGTM, thanks @Narsil!

I'm pretty sure it's normal that the CI doesn't run as long as this isn't on `master`, we had the same issue on transformers a while back.

2021-05-25 14:52 UTC, julien-c approved these changes

2021-05-25 15:40 UTC, merged